---
  - name: install tools
    apt: name={{item}} state=present
    with_items:
      - python-mysqldb
    tags: [ 'packages' ]

  - name: Install mysql-server
    apt: name=mysql-server state=present
    tags: [ 'packages' ]

  - name: ensure mysql listning on all port
    lineinfile: 
      path: /etc/mysql/my.cnf 
      regexp: "^bind-address"
      line: bind-address = "{{ ansible_eth1.ipv4.address }}"
    notify: restart mysql
    tags: [ 'configure' ]

  - name: start mysql-server
    service: name=mysql state=started enabled=yes
    tags: [ 'service' ]
  
  - name: create mysql  database
    mysql_db: name={{db_name}} state=present
    tags: [ 'configure' ]

  - name: create demo user
    mysql_user: name={{db_user_name}} password={{db_user_pass}} priv={{db_name}}.*:ALL host='{{db_user_host}}' state=present
    tags: [ 'configure' ]