---
  - name: install tools
    apt: name={{item}} state=present update_cache=yes
    with_items:
      - python-mysqldb

  - name: Install mysql-server
    apt: name=mysql-server state=present update_cache=yes

  - name: ensure mysql listning on all port
    lineinfile: 
      path: /etc/mysql/my.cnf 
      regexp: "^bind-address"
      line: bind-address = {{ ansible_eth0.ipv4.address }}
    notify: restart mysql

  - name: start mysql-server
    service: name=mysql state=started enabled=yes
  
  - name: create mysql  database
    mysql_db: name=demo state=present

  - name: create demo user
    mysql_user: name=demo password=demo priv=demo.*:ALL host='%' state=present