---
- hosts: loadbalancer
  become: true
  tasks:
    - name: verify nginx
      command: service nginx status

    - name: verify nginx is listning on 80
      wait_for: port=80 timeout=1

- hosts: webserver
  become: true
  tasks:
    - name: verify apache2
      command: service apache2 status

    - name: verify apach2 is listning on 80
      wait_for: port=80 timeout=1

- hosts: database
  become: true
  tasks:
    - name: verify mysql
      command: service mysql status
    
    - name: verify mysql is listning on 3306
      wait_for: port=3306 timeout=1