---
- hosts: loadbalacner
  become: true
  tasks:
    - name: verify nginx
      command: service nginx status

- hosts: webserver
  become: true
  tasks:
    - name: verify apache2
      command: service apache2 status

- hosts: database
  become: true
  tasks:
    - name: verify mysql
      command: service mysql status