---
- hosts: loadbalancer
  become: true
  tasks:
    - name: stop nginx
      service: name=nginx state=stopped
    
- hosts: webserver
  become: true
  tasks:
    - name: stop apache2
      service: name=apache2 state=stopped

- hosts: database
  become: true
  tasks:
    - name: stop mysql
      service: name=mysql state=restarted

- hosts: webserver
  become: true
  tasks:
    - name: start webserver
      service: name=apache2 state=started

- hosts: database
  become: true
  tasks:
    - name: stop mysql
      service: name=mysql state=started
