---
- hosts: webserver
  become: true
  tasks:
    - name: Install apache2
      apt: name={{item}} state=present update_cache=yes
      with_items:
        - apache2
        - libapache2-mod-wsgi
        - python-pip
        - python-virtualenv

    - name: start apache2
      service: name=apache2 satte=started ensure=yes