---
- hosts: webserver
  become: true
  tasks:
    - name: Install apache2
      apt: name={{item}} state=present update_cache=yes
      with_items:
        - apache2
        - libapache2-mod-wsgi
        - python-pip
        - python-virtualenv

    - name: start apache2
      service: name=apache2 state=started enabled=yes

    - name: enable mod_wsgi enabled
      apache2_module: state=present name=wsi
      notify: restart apache2

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
